{% set name = "typepy" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b69fd48b9f50cdb3809906eef36b855b3134ff66c8893a4f8580abddb0b39517

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.3.0
  run:
    - mbstrdecoder >=1.0.0,<2
    - python >={{ python_min }}
    - setuptools >=38.3.0

test:
  imports:
    - typepy
    - typepy.checker
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thombashi/typepy
  summary: typepy is a Python library for variable type checker/validator/converter at a run time.
  dev_url: https://github.com/thombashi/typepy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
