{% set name = "typepy" %}
{% set version = "1.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89c1f66de6c6133209c43a94d23431d320ba03ef5db18f241091ea594035d9de

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - releasecmd
    - pip
  run:
    - python >={{ python_min }}
    - mbstrdecoder >=1.0.0,<2
    - setuptools >=64

test:
  imports:
    - typepy
    - typepy.checker
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thombashi/typepy
  summary: typepy is a Python library for variable type checker/validator/converter at a run time.
  dev_url: https://github.com/thombashi/typepy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
